<a href="https://colab.research.google.com/github/scardonalo-maker/Proyecto-CD-2026-1/blob/main/Preprocesamiento_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv("/content/student_lifestyle_100k (1).csv")
print(df.columns)

Index(['Student_ID', 'Age', 'Gender', 'Department', 'CGPA', 'Sleep_Duration',
       'Study_Hours', 'Social_Media_Hours', 'Physical_Activity',
       'Stress_Level', 'Depression'],
      dtype='object')

In [2]:
print(df["Gender"].unique())

['Female' 'Male']

In [3]:
df["Gender"] = df["Gender"].astype(str)

df["Gender"] = df["Gender"].str.strip().str.lower()

df.loc[df["Gender"] == "male", "Gender"] = 0
df.loc[df["Gender"] == "female", "Gender"] = 1

df["Gender"] = df["Gender"].astype(int)
df

,Student_ID,Age,Gender,Department,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression
0,1001,22,1,Science,3.50,7.3,3.3,3.4,114,5,False
1,1002,20,0,Engineering,2.72,5.5,7.2,6.0,142,2,False
2,1003,20,0,Medical,3.01,5.4,2.3,1.8,137,3,False
3,1004,21,0,Engineering,3.63,8.1,2.0,4.6,130,3,False
4,1005,19,0,Arts,3.14,6.8,2.6,4.3,4,6,False
...,...,...,...,...,...,...,...,...,...,...,...
99995,100996,24,1,Medical,2.02,7.0,0.6,1.4,66,4,False
99996,100997,24,0,Arts,2.33,5.0,3.6,5.2,103,3,False
99997,100998,24,1,Engineering,2.23,6.5,5.8,4.1,61,5,False
99998,100999,19,0,Engineering,3.61,6.1,4.8,4.9,116,4,False
99999,101000,24,1,Medical,2.10,7.9,3.5,4.0,79,4,False

In [4]:
df.drop(columns=["Student_ID"], inplace=True)

In [8]:
df["Department"] = df["Department"].astype(str)

df["Department"] = df["Department"].str.strip().str.lower()

df.loc[df["Department"] == "engineering", "Department"] = 0
df.loc[df["Department"] == "science", "Department"] = 1
df.loc[df["Department"] == "arts", "Department"] = 2
df.loc[df["Department"] == "business", "Department"] = 3
df.loc[df["Department"] == "medical", "Department"] = 4

df["Department"] = df["Department"].astype(int)

print(df["Department"].head())

0    1
1    0
2    4
3    0
4    2
Name: Department, dtype: int64

In [9]:
df

,Age,Gender,Department,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression,dept_engineering,dept_science,dept_arts,dept_business,dept_medical
0,22,1,1,3.50,7.3,3.3,3.4,114,5,False,0,0,0,0,0
1,20,0,0,2.72,5.5,7.2,6.0,142,2,False,0,0,0,0,0
2,20,0,4,3.01,5.4,2.3,1.8,137,3,False,0,0,0,0,0
3,21,0,0,3.63,8.1,2.0,4.6,130,3,False,0,0,0,0,0
4,19,0,2,3.14,6.8,2.6,4.3,4,6,False,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,24,1,4,2.02,7.0,0.6,1.4,66,4,False,0,0,0,0,0
99996,24,0,2,2.33,5.0,3.6,5.2,103,3,False,0,0,0,0,0
99997,24,1,0,2.23,6.5,5.8,4.1,61,5,False,0,0,0,0,0
99998,19,0,0,3.61,6.1,4.8,4.9,116,4,False,0,0,0,0,0
99999,24,1,4,2.10,7.9,3.5,4.0,79,4,False,0,0,0,0,0